### ISSUE TITLE
[4.8.0] Bug: Trying to transfer funds and getting NotEnoughFunds 

### ISSUE THREAD

**Issue by mbiverdev** [hirosystems/desktop-wallet#1164] opened 2023-03-20 15:16 UTC
Hello, team.  I have over 1,000 STX and am only trying to transfer 565 to my other wallet.  I'm getting this NotEnoughFunds message though.  I was just recently stacking on Frieger pool, but revoked delegation.  For a long time it said my stacks were locked, but now that message is gone and I'd like to move some things around.  I've tried installing Hiro desktop on another machine and then restoring the wallet, but same result. NotEnoughFunds .  Any help appreciated.  Thanks.  

Bug found testing Hiro Wallet build undefined, 4.8.0.

**Comment by 314159265359879** [comment] 2023-03-20 16:13
Thanks for reporting. I saw one more user reporting this. I believe it may have something to do with the wallet not considering the STX unlocked. 

Other example
Address: SP3XPB1G2394JKSR8SY9KEJ3J780B4MSXEQP7EDY
![image](https://user-images.githubusercontent.com/33360391/226401656-92b988f9-c9d8-4e5f-b11b-46ccf7736ae9.png)

**Comment by mbiverdev** [comment] 2023-03-20 17:01
So any known resolutions?  Thanks!

**Comment by edu-stx** [comment] 2023-03-20 17:24
For `SP3XPB1G2394JKSR8SY9KEJ3J780B4MSXEQP7EDY`, they can't transfer because they've delegated their stacks,

https://explorer.stacks.co/address/SP3XPB1G2394JKSR8SY9KEJ3J780B4MSXEQP7EDY?chain=mainnet

Currently, their latest transaction is the delegation transaction where they delegate their entire balance,

https://explorer.stacks.co/txid/0x6c5d04989c9c094a3e82747fa86158961453136f81fa926b1ff6ffa2ce3a5259?chain=mainnet

**Comment by edu-stx** [comment] 2023-03-20 17:29
@mbiverdev, not sure if the above address is yours or not. To help me debug the issue, mind sharing with me your address? You can share it privately with me through our discord. Make sure to find me through the admin server list as `edu_stx#6213`.

https://discord.com/channels/1075856098269089834/1075920122314756166

**Comment by mbiverdev** [comment] 2023-03-20 17:31
Strange....I remembered that I did have 35 STX that were not part of the delegation I did a few months back, so I sent 30 to my other wallet, and that completed.  Then I tried to send 100, and that did complete....then I was able to transfer the remaining 435 I wanted to transfer.  So not sure what happened, but doing it in those chunks resolved the issue.

**Comment by rjappels** [comment] 2023-03-20 19:31
I have the same issue, Hiro Wallet 4.8.0. Also with Friedger pool. my address = SPKQVJZM28WJT70G3AP7B0PA5EG4HJ8NH97JK42B

**Comment by rjappels** [comment] 2023-03-20 19:50
some more info

I have delegated my STX in tid 0xde91878b4854247d83da70cb84a28e814932284483520b5a5e0b2795a61a9971
I cannot see this delegation having been revoked, yet since 2 days nothing seems to be locked anymore. When I try to withdraw I get the message "NotEnoughFunds". I check the "actual" and "expected" values it seems that my STX are still locked. 
This is not visible in the wallet. And if I do the api-call: https://stacks-node-api.stacks.co/v2/accounts/SPKQVJZM28WJT70G3AP7B0PA5EG4HJ8NH97JK42B?proof=0 the result shows that there is nothing locked. 
{"balance":"0x0000000000000000000000010e14f62d","locked":"0x00000000000000000000000000000000","unlock_height":0,"nonce":14}

**Comment by 314159265359879** [comment] 2023-03-20 20:42
@rjappels thanks for sharing. 
Would you mind waiting for [this transaction](https://explorer.stacks.co/txid/0xe53e7350e5b1fff43ab25f90a5b240d44c6335bd4cd6bcc8e5d2f95f1d7fa669?chain=mainnet) to settle in an anchorblock then try to send from your address again?

We would test a workaround for this issue https://github.com/stacks-network/stacks-blockchain/issues/3623 that is possibly related.

**Comment by rjappels** [comment] 2023-03-20 21:03
Same result. Something strange though: I can see this transaction has been confirmed in the explorer, however I do not see this in the wallet.

**Comment by rjappels** [comment] 2023-03-20 21:08
relating to the workaround in #3623: I already tried no1 - Send a small amount of STX from a different address to the account they want to unlock. That did not work.

**Comment by 314159265359879** [comment] 2023-03-20 22:12
@rjappels Thanks for checking the workaround. An other user was successful working around the issue by using the Wallet Extension instead. Want to check that out? We have extensions available for Brave, Chrome (with Ledger support) or Firefox.

**Comment by rjappels** [comment] 2023-03-20 22:46
One more thing: planbetter explorer gives a different result than the stacks explorer. The Planbetter explorer seems more in accordance with the experience I have. 
https://explorer.planbetter.org/address/SPKQVJZM28WJT70G3AP7B0PA5EG4HJ8NH97JK42B?chain=mainnet
https://explorer.stacks.co/address/SP1ZM8RBGTF44565HYXEHN6EF1FYJ7XYGTJCZT6Q6?chain=mainnet

and ... I will check the workaround with the Wallet Extension later.

**Comment by rjappels** [comment] 2023-03-20 22:48
sorry wrong stacks explorer link. Here's the right one.
https://explorer.stacks.co/address/SPKQVJZM28WJT70G3AP7B0PA5EG4HJ8NH97JK42B?chain=mainnet

**Comment by rjappels** [comment] 2023-03-20 22:54
it seems that the https://explorer.stacks.co (used by the stacks wallet, i believe) does not display the locked STX. 
see also
https://explorer.stacks.co/address/SP1ZM8RBGTF44565HYXEHN6EF1FYJ7XYGTJCZT6Q6?chain=mainnet
https://explorer.planbetter.org/address/SP1ZM8RBGTF44565HYXEHN6EF1FYJ7XYGTJCZT6Q6?chain=mainnet
I use this address with xverse and in that app everything seems normal

**Comment by 314159265359879** [comment] 2023-03-21 07:39
The planbetter explorer did not yet upgrade to Stacks 2.1 it hasn’t
received updates since the new consensus rules activated (last block 2 days
ago).

Unlocked STX are expected because of the switch to PoX2

**Comment by rjappels** [comment] 2023-03-21 08:57
Hi thx for the info! Does this mean I can assume my STX are unlocked because of the upgrade?? if so... my problem is still not solved. I still cannot withdraw my STX.

**Comment by 314159265359879** [comment] 2023-03-21 13:02
This looks like the root cause: https://github.com/stacks-network/stacks-blockchain/issues/3623

It does not look like the Extension is providing a viable workaround, unlocked STX appears locked because of a protocol bug. 

The issue does describe three other possible workarounds. 
This is a solution that works and has been confirmed twice now: https://github.com/hirosystems/desktop-wallet/issues/1164/#issuecomment-1476655083

A. **If you know you had a couple STX not stacking in the wallet prior to Stacks 2.1 activating you can simply use the Desktop wallet to send to one of your other addresses or the burn address.** 

B. The Hiro wallet extension can still help because it allows sending the smallest amount and editing the a custom fee to the lowest amount possible. 

Using the extension you can unlock with a minimum of 0.000181 STX:
1. send 0.000001 STX to any address (for example the burn address: SP000000000000000000002Q6VF78
2. Set a custom fee to 0.00018 STX (lowest possible)

**Comment by rjappels** [comment] 2023-03-21 20:56
Hi, option B (send small amount from extension) did the trick for me. Thx!!

**Comment by 314159265359879** [comment] 2023-03-22 10:39
This issue has been resolved by an update of the blockchain node software. 2.1.0.0.2 we'll start seeing less of this as nodes upgrade.

**Closed by 314159265359879** 2023-03-22 10:39 UTC
Labels: Bug 🐛, P1 Bug 🚨, stacking, Stacks 2.1

**Comment by 314159265359879** [comment] 2023-03-29 07:41
it doesn't look like this is completely resolved. The problem just changed. 

Now users can send the transaction but miners are not picking it up. would that be the case if user connect to an upgraded node (2.1.0.0.2) but miners are not running the 2.1.0.0.2 upgrade? 

![image](https://user-images.githubusercontent.com/33360391/228461340-b4ba2926-376a-431c-8877-62c577dafa35.png)

I have seen more. Still troubleshooting with users to confirm.

**Comment by 314159265359879** [comment] 2023-03-29 09:57
Fixed above issue with two transactions. 
1. small transfer to "unlock" stacks
2. releasing the STX to send elsewhere
![image](https://user-images.githubusercontent.com/33360391/228485612-be992568-0c47-4592-b20e-5ea48d131e94.png)

**Comment by 314159265359879** [comment] 2023-03-29 21:53
One more confirmed case unlocked getting mined by sending a small transaction
This wallet: SP2F8ZHYZ7SQCYE6ASJ0F3T0R0M0D5JH5KGT73HF8

![image](https://user-images.githubusercontent.com/33360391/228665439-e22a375d-83a0-4316-9190-97d2df7f0e86.png)


And another one
SPQBS5WW0CF8SVEH2J26T89N7ZVX117CWTRKJG1A
![image](https://user-images.githubusercontent.com/33360391/228675674-36db867a-1a05-43aa-946a-71de6323a1f5.png)



Workaround works when you have pending transactions but only by using the Hiro Wallet Extension (that supports editing the nonce and setting a custom fee). 
1. Make a new transaction 
2. To send 0.000001 STX
to this address: SP000000000000000000002Q6VF78 
3. Set a custom fee of exactly 0.072001 STX (this should be 0.000001 STX more than the current transaction with the next nonce that can be processed (account nonce +1)
4. Edit the nonce to the nonce of the transaction you are trying to replace
